version: '3'

services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app

  influxdb:
    image: influxdb:2.6.1
    container_name: influxdb4.0
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2
      - ./data/influxdb/config:/etc/influxdb2

  grafana:
    image: grafana/grafana:8.2.6
    container_name: grafana4.0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana/data:/var/lib/grafana
      - ./data/grafana/provisioning:/etc/grafana/provisioning
    user: "472:472"
    
  nodered:
    image: nodered/node-red:latest
    container_name: nodered4.0
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./data/nodered/data:/data
    user: "1000:1000"
    